"""initial schema

Recreates the full SCHOLARIS schema (31 tables) as a single frozen
baseline revision.  Every CREATE is guarded with an existence check so the
revision can be stamped/run safely on both:
  * a fresh database (creates everything), and
  * a legacy production database that already has most tables (creates only
    what is missing; legacy drift is reconciled by revision 0002).

Revision ID: 0001
Revises:
Create Date: 2026-10-01
"""
from typing import Sequence, Union

from alembic import op as _op
from alembic import op
import sqlalchemy as sa
import sqlalchemy as _sa


def _inspector():
    return _sa.inspect(_op.get_bind())


def _table_exists(name: str) -> bool:
    return _inspector().has_table(name)


def _index_exists(table: str, name: str) -> bool:
    try:
        return any(ix["name"] == name for ix in _inspector().get_indexes(table))
    except Exception:
        return False


def _create_table(name: str, *args, **kwargs) -> None:
    if not _table_exists(name):
        _op.create_table(name, *args, **kwargs)


def _create_index(name: str, table: str, columns, **kwargs) -> None:
    if not _table_exists(table) or not _index_exists(table, name):
        _op.create_index(name, table, columns, **kwargs)


def _drop_index(name: str, table: str = None, table_name: str = None, **kwargs) -> None:
    table = table or table_name
    if table and _table_exists(table) and _index_exists(table, name):
        _op.drop_index(name, table_name=table, **kwargs)


def _drop_table(name: str) -> None:
    if _table_exists(name):
        _op.drop_table(name)




# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('SUPER_ADMIN', 'PRINCIPAL', 'TEACHER', 'STUDENT', name='userrole'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    _create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    _create_table('schools',
    sa.Column('school_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_name', sa.String(length=150), nullable=False),
    sa.Column('school_code', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('school_id')
    )
    _create_index(op.f('ix_schools_school_code'), 'schools', ['school_code'], unique=True)
    _create_index(op.f('ix_schools_school_id'), 'schools', ['school_id'], unique=False)
    _create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(length=255), nullable=False),
    sa.Column('platform_logo', sa.String(length=500), nullable=True),
    sa.Column('default_language', sa.String(length=10), nullable=False),
    sa.Column('time_zone', sa.String(length=50), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('email_configuration', sa.JSON(), nullable=True),
    sa.Column('backup_settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _create_table('academic_years',
    sa.Column('academic_year_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('year_name', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('academic_year_id'),
    sa.UniqueConstraint('school_id', 'year_name', name='uq_school_academic_year')
    )
    _create_index(op.f('ix_academic_years_academic_year_id'), 'academic_years', ['academic_year_id'], unique=False)
    _create_index(op.f('ix_academic_years_school_id'), 'academic_years', ['school_id'], unique=False)
    _create_index(op.f('ix_academic_years_status'), 'academic_years', ['status'], unique=False)
    _create_table('calendar_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index(op.f('ix_calendar_events_id'), 'calendar_events', ['id'], unique=False)
    _create_index(op.f('ix_calendar_events_school_id'), 'calendar_events', ['school_id'], unique=False)
    _create_index(op.f('ix_calendar_events_start_date'), 'calendar_events', ['start_date'], unique=False)
    _create_table('grades',
    sa.Column('grade_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('grade_name', sa.String(length=30), nullable=False),
    sa.Column('grade_code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('grade_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grade_id'),
    sa.UniqueConstraint('school_id', 'grade_name', name='uq_school_grade_name')
    )
    _create_index(op.f('ix_grades_grade_id'), 'grades', ['grade_id'], unique=False)
    _create_index(op.f('ix_grades_school_id'), 'grades', ['school_id'], unique=False)
    _create_table('school_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.Column('school_logo', sa.String(length=500), nullable=True),
    sa.Column('school_address', sa.String(length=500), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('academic_year', sa.String(length=50), nullable=True),
    sa.Column('school_working_days', sa.JSON(), nullable=True),
    sa.Column('school_timings', sa.String(length=100), nullable=True),
    sa.Column('grade_settings', sa.JSON(), nullable=True),
    sa.Column('section_settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index(op.f('ix_school_settings_school_id'), 'school_settings', ['school_id'], unique=True)
    _create_table('subjects',
    sa.Column('subject_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('subject_code', sa.String(length=30), nullable=True),
    sa.Column('is_elective', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('school_id', 'subject_name', name='uq_school_subject_name')
    )
    _create_index(op.f('ix_subjects_school_id'), 'subjects', ['school_id'], unique=False)
    _create_index(op.f('ix_subjects_subject_id'), 'subjects', ['subject_id'], unique=False)
    _create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('profile_photo', sa.String(length=255), nullable=True),
    sa.Column('reset_token', sa.String(length=128), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'PRINCIPAL', 'TEACHER', 'STUDENT'), nullable=False),
    sa.Column('account_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id')
    )
    _create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    _create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=False)
    _create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    _create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    _create_index(op.f('ix_users_school_id'), 'users', ['school_id'], unique=False)
    _create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    _create_table('announcements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('target_role', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status_value', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index(op.f('ix_announcements_created_by'), 'announcements', ['created_by'], unique=False)
    _create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    _create_index(op.f('ix_announcements_school_id'), 'announcements', ['school_id'], unique=False)
    _create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    _create_index('idx_audit_school_timestamp', 'audit_logs', ['school_id', 'timestamp'], unique=False)
    _create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    _create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    _create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    _create_index(op.f('ix_audit_logs_school_id'), 'audit_logs', ['school_id'], unique=False)
    _create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    _create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    _create_table('principal_profiles',
    sa.Column('principal_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=30), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('principal_id')
    )
    _create_index(op.f('ix_principal_profiles_principal_id'), 'principal_profiles', ['principal_id'], unique=False)
    _create_index(op.f('ix_principal_profiles_school_id'), 'principal_profiles', ['school_id'], unique=False)
    _create_index(op.f('ix_principal_profiles_user_id'), 'principal_profiles', ['user_id'], unique=True)
    _create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('replaced_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    _create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    _create_table('students',
    sa.Column('student_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('admission_number', sa.String(length=30), nullable=True),
    sa.Column('roll_number', sa.String(length=50), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('father_name', sa.String(length=100), nullable=True),
    sa.Column('father_mobile', sa.String(length=15), nullable=True),
    sa.Column('mother_name', sa.String(length=100), nullable=True),
    sa.Column('mother_mobile', sa.String(length=15), nullable=True),
    sa.Column('guardian_mobile', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('student_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    _create_index(op.f('ix_students_school_id'), 'students', ['school_id'], unique=False)
    _create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=False)
    _create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    _create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('qualification', sa.String(length=100), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    _create_index(op.f('ix_teachers_school_id'), 'teachers', ['school_id'], unique=False)
    _create_index(op.f('ix_teachers_teacher_id'), 'teachers', ['teacher_id'], unique=False)
    _create_index(op.f('ix_teachers_user_id'), 'teachers', ['user_id'], unique=True)
    _create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index('idx_upload_entity', 'uploads', ['entity_type', 'entity_id'], unique=False)
    _create_index('idx_upload_school_owner', 'uploads', ['school_id', 'uploaded_by_id'], unique=False)
    _create_index(op.f('ix_uploads_entity_id'), 'uploads', ['entity_id'], unique=False)
    _create_index(op.f('ix_uploads_entity_type'), 'uploads', ['entity_type'], unique=False)
    _create_index(op.f('ix_uploads_id'), 'uploads', ['id'], unique=False)
    _create_index(op.f('ix_uploads_school_id'), 'uploads', ['school_id'], unique=False)
    _create_index(op.f('ix_uploads_uploaded_by_id'), 'uploads', ['uploaded_by_id'], unique=False)
    _create_table('user_app_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_information', sa.JSON(), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index(op.f('ix_user_app_settings_user_id'), 'user_app_settings', ['user_id'], unique=True)
    _create_table('grade_subjects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.grade_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_id', 'subject_id', name='uq_grade_subject')
    )
    _create_index(op.f('ix_grade_subjects_grade_id'), 'grade_subjects', ['grade_id'], unique=False)
    _create_index(op.f('ix_grade_subjects_id'), 'grade_subjects', ['id'], unique=False)
    _create_index(op.f('ix_grade_subjects_subject_id'), 'grade_subjects', ['subject_id'], unique=False)
    _create_index(op.f('ix_grade_subjects_teacher_id'), 'grade_subjects', ['teacher_id'], unique=False)
    _create_table('sections',
    sa.Column('section_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=10), nullable=False),
    sa.Column('class_teacher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_teacher_id'], ['teachers.teacher_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.grade_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('section_id'),
    sa.UniqueConstraint('grade_id', 'section_name', name='uq_grade_section_name')
    )
    _create_index(op.f('ix_sections_grade_id'), 'sections', ['grade_id'], unique=False)
    _create_index(op.f('ix_sections_school_id'), 'sections', ['school_id'], unique=False)
    _create_index(op.f('ix_sections_section_id'), 'sections', ['section_id'], unique=False)
    _create_table('attendance_records',
    sa.Column('attendance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'LEAVE', 'VOID', name='attendance_status'), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.academic_year_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attendance_id'),
    sa.UniqueConstraint('student_id', 'date', name='uq_student_attendance_date')
    )
    _create_index('idx_attendance_year_section_date', 'attendance_records', ['academic_year_id', 'section_id', 'date'], unique=False)
    _create_index(op.f('ix_attendance_records_academic_year_id'), 'attendance_records', ['academic_year_id'], unique=False)
    _create_index(op.f('ix_attendance_records_attendance_id'), 'attendance_records', ['attendance_id'], unique=False)
    _create_index(op.f('ix_attendance_records_date'), 'attendance_records', ['date'], unique=False)
    _create_index(op.f('ix_attendance_records_section_id'), 'attendance_records', ['section_id'], unique=False)
    _create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    _create_table('exams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exam_type', sa.String(length=100), nullable=False),
    sa.Column('assessment_mode', sa.Enum('FORMATIVE', 'SUMMATIVE', name='exam_assessment_mode'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'MARKS_IN_PROGRESS', 'PUBLISHED', 'ARCHIVED', name='exam_status'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.academic_year_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.grade_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index(op.f('ix_exams_academic_year_id'), 'exams', ['academic_year_id'], unique=False)
    _create_index(op.f('ix_exams_grade_id'), 'exams', ['grade_id'], unique=False)
    _create_index(op.f('ix_exams_id'), 'exams', ['id'], unique=False)
    _create_index(op.f('ix_exams_school_id'), 'exams', ['school_id'], unique=False)
    _create_index(op.f('ix_exams_section_id'), 'exams', ['section_id'], unique=False)
    _create_table('homework',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.academic_year_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.grade_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index(op.f('ix_homework_academic_year_id'), 'homework', ['academic_year_id'], unique=False)
    _create_index(op.f('ix_homework_grade_id'), 'homework', ['grade_id'], unique=False)
    _create_index(op.f('ix_homework_id'), 'homework', ['id'], unique=False)
    _create_index(op.f('ix_homework_school_id'), 'homework', ['school_id'], unique=False)
    _create_index(op.f('ix_homework_section_id'), 'homework', ['section_id'], unique=False)
    _create_index(op.f('ix_homework_subject_id'), 'homework', ['subject_id'], unique=False)
    _create_index(op.f('ix_homework_teacher_id'), 'homework', ['teacher_id'], unique=False)
    _create_table('notifications',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('sender_user_id', sa.Integer(), nullable=True),
    sa.Column('sender_role', sa.String(length=50), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('target_class_id', sa.Integer(), nullable=True),
    sa.Column('target_student_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_class_id'], ['sections.section_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    _create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=False)
    _create_index(op.f('ix_notifications_school_id'), 'notifications', ['school_id'], unique=False)
    _create_index(op.f('ix_notifications_sender_user_id'), 'notifications', ['sender_user_id'], unique=False)
    _create_index(op.f('ix_notifications_target_class_id'), 'notifications', ['target_class_id'], unique=False)
    _create_index(op.f('ix_notifications_target_student_id'), 'notifications', ['target_student_id'], unique=False)
    _create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    _create_table('student_enrollments',
    sa.Column('enrollment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('roll_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.academic_year_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enrollment_id'),
    sa.UniqueConstraint('academic_year_id', 'section_id', 'roll_number', name='uq_academic_section_roll'),
    sa.UniqueConstraint('student_id', 'academic_year_id', name='uq_student_year_enrollment')
    )
    _create_index(op.f('ix_student_enrollments_academic_year_id'), 'student_enrollments', ['academic_year_id'], unique=False)
    _create_index(op.f('ix_student_enrollments_enrollment_id'), 'student_enrollments', ['enrollment_id'], unique=False)
    _create_index(op.f('ix_student_enrollments_section_id'), 'student_enrollments', ['section_id'], unique=False)
    _create_index(op.f('ix_student_enrollments_student_id'), 'student_enrollments', ['student_id'], unique=False)
    _create_table('teacher_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.academic_year_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.grade_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'academic_year_id', 'grade_id', 'section_id', 'subject_id', name='uq_teacher_subject_year_class_subject')
    )
    _create_index('idx_class_subject_assignment', 'teacher_subjects', ['grade_id', 'section_id', 'subject_id'], unique=False)
    _create_index('idx_teacher_assignments', 'teacher_subjects', ['teacher_id', 'school_id'], unique=False)
    _create_index(op.f('ix_teacher_subjects_academic_year_id'), 'teacher_subjects', ['academic_year_id'], unique=False)
    _create_index(op.f('ix_teacher_subjects_grade_id'), 'teacher_subjects', ['grade_id'], unique=False)
    _create_index(op.f('ix_teacher_subjects_id'), 'teacher_subjects', ['id'], unique=False)
    _create_index(op.f('ix_teacher_subjects_school_id'), 'teacher_subjects', ['school_id'], unique=False)
    _create_index(op.f('ix_teacher_subjects_section_id'), 'teacher_subjects', ['section_id'], unique=False)
    _create_index(op.f('ix_teacher_subjects_subject_id'), 'teacher_subjects', ['subject_id'], unique=False)
    _create_index(op.f('ix_teacher_subjects_teacher_id'), 'teacher_subjects', ['teacher_id'], unique=False)
    _create_table('timetables',
    sa.Column('timetable_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('room_number', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.academic_year_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.grade_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('timetable_id')
    )
    _create_index(op.f('ix_timetables_academic_year_id'), 'timetables', ['academic_year_id'], unique=False)
    _create_index(op.f('ix_timetables_grade_id'), 'timetables', ['grade_id'], unique=False)
    _create_index(op.f('ix_timetables_school_id'), 'timetables', ['school_id'], unique=False)
    _create_index(op.f('ix_timetables_section_id'), 'timetables', ['section_id'], unique=False)
    _create_index(op.f('ix_timetables_subject_id'), 'timetables', ['subject_id'], unique=False)
    _create_index(op.f('ix_timetables_teacher_id'), 'timetables', ['teacher_id'], unique=False)
    _create_index(op.f('ix_timetables_timetable_id'), 'timetables', ['timetable_id'], unique=False)
    _create_table('exam_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('written_test', sa.Float(), nullable=False),
    sa.Column('project', sa.Float(), nullable=False),
    sa.Column('read_reflection', sa.Float(), nullable=False),
    sa.Column('notebook', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'student_id', 'subject_id', name='uq_exam_student_subject_result')
    )
    _create_index(op.f('ix_exam_results_exam_id'), 'exam_results', ['exam_id'], unique=False)
    _create_index(op.f('ix_exam_results_id'), 'exam_results', ['id'], unique=False)
    _create_index(op.f('ix_exam_results_student_id'), 'exam_results', ['student_id'], unique=False)
    _create_index(op.f('ix_exam_results_subject_id'), 'exam_results', ['subject_id'], unique=False)
    _create_table('exam_subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('maximum_marks', sa.Float(), nullable=False),
    sa.Column('passing_marks', sa.Float(), nullable=False),
    sa.Column('is_marks_submitted', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'subject_id', name='uq_exam_subject')
    )
    _create_index(op.f('ix_exam_subjects_exam_date'), 'exam_subjects', ['exam_date'], unique=False)
    _create_index(op.f('ix_exam_subjects_exam_id'), 'exam_subjects', ['exam_id'], unique=False)
    _create_index(op.f('ix_exam_subjects_id'), 'exam_subjects', ['id'], unique=False)
    _create_index(op.f('ix_exam_subjects_subject_id'), 'exam_subjects', ['subject_id'], unique=False)
    _create_index(op.f('ix_exam_subjects_teacher_id'), 'exam_subjects', ['teacher_id'], unique=False)
    _create_table('report_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('term_name', sa.String(length=100), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('grade_letter', sa.String(length=10), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.academic_year_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'academic_year_id', 'exam_id', 'term_name', name='uq_student_exam_term_report_card')
    )
    _create_index(op.f('ix_report_cards_academic_year_id'), 'report_cards', ['academic_year_id'], unique=False)
    _create_index(op.f('ix_report_cards_exam_id'), 'report_cards', ['exam_id'], unique=False)
    _create_index(op.f('ix_report_cards_id'), 'report_cards', ['id'], unique=False)
    _create_index(op.f('ix_report_cards_student_id'), 'report_cards', ['student_id'], unique=False)
    _create_table('user_notifications',
    sa.Column('user_notification_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.notification_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_notification_id')
    )
    _create_index(op.f('ix_user_notifications_notification_id'), 'user_notifications', ['notification_id'], unique=False)
    _create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    _create_index(op.f('ix_user_notifications_user_notification_id'), 'user_notifications', ['user_notification_id'], unique=False)
    _create_table('marks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_subject_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('marks_obtained', sa.Float(), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('entered_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('marks_obtained >= 0', name='chk_marks_obtained_positive'),
    sa.ForeignKeyConstraint(['entered_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_subject_id', 'student_id', name='uq_exam_subject_student_marks')
    )
    _create_index('idx_marks_school_exam_subject', 'marks', ['school_id', 'exam_subject_id'], unique=False)
    _create_index('idx_marks_student_exam_subject', 'marks', ['student_id', 'exam_subject_id'], unique=False)
    _create_index(op.f('ix_marks_exam_subject_id'), 'marks', ['exam_subject_id'], unique=False)
    _create_index(op.f('ix_marks_id'), 'marks', ['id'], unique=False)
    _create_index(op.f('ix_marks_school_id'), 'marks', ['school_id'], unique=False)
    _create_index(op.f('ix_marks_student_id'), 'marks', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop every table created by this revision, children first (reverse of
    # the creation order above). Dropping the table removes its indexes and
    # constraints together, which MySQL requires - an index that backs a
    # foreign key cannot be dropped independently (error 1553).
    for table in [
        'marks',
        'user_notifications',
        'report_cards',
        'exam_subjects',
        'exam_results',
        'timetables',
        'teacher_subjects',
        'student_enrollments',
        'notifications',
        'homework',
        'exams',
        'attendance_records',
        'sections',
        'grade_subjects',
        'user_app_settings',
        'uploads',
        'teachers',
        'students',
        'refresh_tokens',
        'principal_profiles',
        'audit_logs',
        'announcements',
        'users',
        'subjects',
        'school_settings',
        'grades',
        'calendar_events',
        'academic_years',
        'system_settings',
        'schools',
        'roles',
    ]:
        _drop_table(table)
